PLATFORMS: list[tuple[str, str]] = [
    ("AllRecipes", "https://www.allrecipes.com/search?q={query}"),
    ("Amazon", "https://www.amazon.com/s?k={query}"),
    ("Bluesky", "https://bsky.app/search?q={query}"),
    ("Etsy", "https://www.etsy.com/search?q={query}"),
    ("Facebook", "https://www.facebook.com/search/top/?q={query}"),
    ("Flickr", "https://www.flickr.com/search/?text={query}"),
    ("Google Books", "https://www.google.com/search?q={query}&tbm=bks"),
    ("Google Images", "https://www.google.com/search?q={query}&tbm=isch"),
    ("Google News", "https://www.google.com/search?q={query}&tbm=nws"),
    ("Google Scholar", "https://scholar.google.com/scholar?q={query}"),
    ("Google Videos", "https://www.google.com/search?q={query}&tbm=vid"),
    ("Google", "https://www.google.com/search?q={query}"),
    ("Instagram", "https://www.instagram.com/explore/search/keyword/?q={query}"),
    ("King Arthur Baking", "https://www.kingarthurbaking.com/search?q={query}"),
    ("Medium", "https://medium.com/search?q={query}"),
    ("Pinterest", "https://www.pinterest.com/search/pins/?q={query}"),
    ("Quora", "https://www.quora.com/search?q={query}"),
    ("Reddit", "https://www.reddit.com/search/?q={query}"),
    ("Substack", "https://substack.com/search/{query}"),
    ("Threads", "https://www.threads.net/search?q={query}"),
    ("TikTok", "https://www.tiktok.com/search?q={query}"),
    ("Tumblr", "https://www.tumblr.com/search/{query}"),
    ("Twitter / X", "https://x.com/search?q={query}"),
    ("Vimeo", "https://vimeo.com/search?q={query}"),
    ("Wikipedia", "https://en.wikipedia.org/w/index.php?search={query}"),
    ("YouTube", "https://www.youtube.com/results?search_query={query}"),
]
